package lpda.SistemaHotelero.features.roles.enums;

public enum Permiso {
    VER_HABITACIONES,
    CREAR_HABITACION,
    ACTUALIZAR_HABITACION,
    CAMBIAR_ESTADO_LIMPIEZA,
    CAMBIAR_ESTADO_OCUPACION,

    VER_RESERVAS,
    CREAR_RESERVA,
    ACTUALIZAR_RESERVA,
    CANCELAR_RESERVA,

    VER_HUESPEDES,
    CREAR_HUESPED,
    ACTUALIZAR_HUESPED,

    REALIZAR_CHECK_IN,
    REALIZAR_CHECK_OUT,

    VER_PAGOS,
    REGISTRAR_PAGO,

    VER_USUARIOS,
    CREAR_USUARIO,
    ACTUALIZAR_USUARIO,
    ELIMINAR_USUARIO
}
